name: Upload Website

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Upload to S3
            - uses: actions/checkout@master
            - uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.gitignore' --exclude '.github/*'
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: "eu-central-1" # optional: defaults to us-east-1

            # Invalidate Cloudfront (this action)
            - name: invalidate
              uses: chetan/invalidate-cloudfront-action@master
              env:
                  DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
                  PATHS: "/*"
                  AWS_REGION: "eu-central-1"
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
